name    'brucem-jetty'
version '0.0.1'
source 'git@github.com:brucem/puppet-jetty.git'
author 'Bruce Morrison'
license 'Apache License, Version 2.0'
summary 'Jetty Module'
description 'A puppet module for managing Jetty installation and configuration'
project_page 'https://github.com/brucem/puppet-jetty'
dependency 'puppetlabs/java', '>= 0.3.0'
